services:
  - type: web
    name: pillbot-ultra
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python pill_bot_ultra_render.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: TZ
        value: Asia/Tashkent
