
services:
  - type: web
    name: pillbot-4-4-interactive
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python webhook_app.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ENABLE_VOICE
        value: "True"
      - key: VOICE_LANG
        value: "uz"
      - key: KEEPALIVE_PORT
        value: "10000"
      - key: USE_WEBHOOK
        value: "True"
      - key: BASE_URL
        value: "https://pillbot-ultra-pro-max.onrender.com"
      - key: DEFAULT_TIMEZONE
        value: "Asia/Tashkent"
